# Generated by Django 3.1.2 on 2020-10-03 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_remove_deal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='final_votes',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(default='8583334444', max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='items',
            field=models.ManyToManyField(to='restaurants.Item'),
        ),
    ]
