# Generated by Django 3.1.2 on 2020-10-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20201003_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='deal',
            name='img_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.CharField(max_length=1000),
        ),
    ]
