# Generated by Django 3.1.2 on 2020-10-03 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_auto_20201003_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
